### ISSUE TITLE
When a server has Custom Crops plugin, this mod couldn't detect right noteblocks, so I modified your code.

### ISSUE THREAD

**Issue by euichan41** [Nat1anWasTaken/Notebot#5]
Hey there, I'm one of your notebot mod users.

But when a server has Custom Crops plugin, this notebot mod doesn't work properly.

Since the Custom Crops plugin uses noteblocks with each instruments and pitches as custom blocks, every noteblock has same instrument as harp, regardless of what instrument block is placed under the noteblock. 

Therefore, unless this notebot mod reads the current blockstate of noteblocks, the notebot didn't work in the server.

So I changed the code: 

I made the mod detect the block right under the playable noteblock, instead of reading the blockstate of noteblocks.

( Here's the code I edited:  [https://github.com/euichan41/Notebot_euichan41] )

I replaced the "getInstrument" method into "getInstrumentUnderneath" method, which detects the block underneath.

Also in the "loadSong" method, I added a snippet of code that sends error message not only with the number of missing noteblocks, but also the name of missing instruments. Like this:
![image](https://github.com/Nat1anWasTaken/Notebot/assets/98069399/b4ea1aa2-c798-45b2-be7f-472f89ea0343)

Plus, This notebot mod reads the Hat(sand) notes in a nbs file as Bass(wood), so I edited NotebotUtils.java file to read it right.

![image](https://github.com/Nat1anWasTaken/Notebot/assets/98069399/ca2126d7-7c40-4db6-993e-3aa937ecf190)

Please review the code I've linked above, and I hope my edits will be incorporated into your notebot code.

**Comment by Nat1anWasTaken** [comment]
Thanks for pointing that out! Can you open a PR for the fixes so I can merge them?

**Comment by euichan41** [comment]
Sure! I opened a PR with changes in two files.

**Comment by Nat1anWasTaken** [comment]
Thanks for your contribution! I've merged the PR, so I will close this issue. If you have any further question or bug report, feel free to open another issue or contact me on Discord (Nat1an#0001)!
